#!/usr/bin/env bash
# Generate a hardened .env for an internet-exposed Postcard deployment.
#
# The compose stack already boots with safe defaults for a local/home deploy,
# so this is OPTIONAL. Run it when you expose the instance publicly and want
# unique, random internal secrets.
#
#   ./scripts/gen-secrets.sh          # create .env (won't overwrite an existing one)
#   ./scripts/gen-secrets.sh --force  # overwrite an existing .env
set -euo pipefail

cd "$(dirname "$0")/.."

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ -f .env ] && [ "$FORCE" -ne 1 ]; then
  echo ".env already exists — pass --force to overwrite." >&2
  exit 1
fi

# Prefer openssl; fall back to /dev/urandom.
rand() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

PARSE_MASTER_KEY="$(rand)"
MONGO_PASSWORD="$(rand)"

cp .env.example .env

# Append (later assignments win in docker compose's env-file parsing).
{
  echo ""
  echo "# --- Generated by scripts/gen-secrets.sh ---"
  echo "PARSE_MASTER_KEY=${PARSE_MASTER_KEY}"
  echo "MONGO_PASSWORD=${MONGO_PASSWORD}"
} >> .env

echo "Wrote .env with freshly generated PARSE_MASTER_KEY and MONGO_PASSWORD."
echo "Next: set NUXT_AI_API_KEY in .env to enable the AI assistant, then run:"
echo "  docker compose up -d --build"
